pipeline {
  agent any

  options {
    skipDefaultCheckout(true)   // prevents the auto checkout stage duplication
    timestamps()
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init') {
      steps {
        dir('terraform-jenkins') {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Validate') {
      steps {
        dir('terraform-jenkins') {
          sh 'terraform validate'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir('terraform-jenkins') {
          sh 'terraform plan'
        }
      }
    }
  }
}

